name: Generate Tag Pages

on:
  push:
    branches: [ main ]  # or replace with your default branch

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.1'

    - name: Run tag generator script
      run: ruby generate_tags.rb

    - name: Commit & push tag pages
      env:
        GH_PAT: ${{ secrets.GH_PAT }}
      run: |
        git config user.name "GloriaXie"
        git config user.email "guohuanxie@foxmail.com"
        git remote set-url origin https://x-access-token:${GH_PAT}@github.com/${{ github.repository }}
        git add tag/
        git commit -m "Auto-generate tag pages" || echo "No changes to commit"
        git push origin HEAD:main



