name: Generate Tag Pages

on:
  push:
    branches: [ main ]  # or your default branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.1'

    - name: Run generate_tags.rb
      run: ruby generate_tags.rb

    - name: Commit & push tag pages
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add tag/
        git commit -m "Auto-generate tag pages" || echo "No changes to commit"
        git push
